### ISSUE TITLE
Implement fees

### ISSUE THREAD

**Issue by imprfekt** [StreamFlow-Finance/streamflow-timelock#13]
Build with @parazyd and on top of his changes.

As outlined here and during our call:
https://docs.google.com/document/d/1z7rhs6UIlgM5NmHFYTARtEeKdz5PS2nXptnxJq_jGgo/edit#

Additionally (other tasks fit in here):
Implement (on new branch `fees`) TODOs from `token.rs` and `state.rs`
Skip:
   -  converting float to int arithmetics
   - wrapped SOL
   - closing metadata account

Implement customizable options (as discussed here: #9)

ty 🙏

**Comment by nemanjab17** [comment]
Todo after refactor:

- [x] handle withdraw amount
- [x] withdraw verify authority
- [x] sync balance with withdrawn amount
- [x] add fee oracle PDA account to instructions

Discovered during CR:
- [x] remove closable_at (calculate `end_date` (based on the release rate, deposited, start date) and use as only reference)
- [x] on create, check lamports for rent, and transaction fee similar to https://github.com/StreamFlow-Finance/timelock-crate/blob/master/src/token.rs#L140
- [x] change duration sanity, end_date is not calculated
- [x] remove release rate from CreateParams
- [ ] make `stream_name`fixed length, so we can add different fields to the contract (metadata) without introducing breaking changes
- [x] calculate if sender has enough funds to cover all the fees (our/partner token fees, tx fees, rent fees)
- [ ] if recipient account empty (just created), transfer 2 x 5000 lamports to the recipient (one for the initial withdrawal, one for the swap)

**Comment by imprfekt** [comment]
pravimo novi
