### ISSUE TITLE
Add constant prefix for metadata seed?

### ISSUE THREAD

**Issue by imprfekt** [StreamFlow-Finance/streamflow-timelock#20]
Ovo je TODO koji si ostavio na nekoliko mesta u kodu:
    // TODO: Needs a deterministic seed and **metadata** should become a PDA

Sta je zakljucak (nakon prepiske sa auditorima) moze li se odraditi tako? :)

**Comment by parazyd** [comment]
On 28 December 2021 18:07:51 CET, imprfekt ***@***.***> wrote:
>Ovo je TODO koji si ostavio na nekoliko mesta u kodu:
>    // TODO: Needs a deterministic seed and **metadata** should become a PDA
>
>Sta je zakljucak (nakon prepiske sa auditorima) moze li se odraditi tako? :)
>

Auditori su rekli da je postojece ok, tako da TODO moze da se brise. Dodacemo samo konstantni prefiks.

**Comment by imprfekt** [comment]
Kul, tnx! 

Onda brisni todos i zatvori issue nakon sto dodas prefix (kapiram nesto tipa "strm" ?) :)
