### ISSUE TITLE
Internal security audit

### ISSUE THREAD

**Issue by nemanjab17** [StreamFlow-Finance/streamflow-timelock#22]
Analyze crate code based on [solend bug bounty](https://docs.solend.fi/security/bug-bounty)

- [ ] detailed security audit https://blog.neodyme.io/posts/solana_common_pitfalls
- [ ] use Soteria toolkit https://www.soteria.dev/post/soteria-a-vulnerability-scanner-for-solana-smart-contracts (preferably within a VM)

This is **super important**! 🙏

**Comment by imprfekt** [comment]
Soteria toolkit
