### ISSUE TITLE
Limit maximum deposit to a certain number (discuss) to prevent overflows in program

### ISSUE THREAD

**Issue by nemanjab17** [StreamFlow-Finance/streamflow-timelock#26]

**Comment by nemanjab17** [comment]
There is a calculation of gross amount on contract create (deposit + fees), and if net amount is a bit below u64::MAX (1.84 * 10^19) which is 1.84 * 10^10 tokens, it can overflow when fees are added (they can be 1% of deposit tops)

**Comment by imprfekt** [comment]
We should use checked arithmetics for this. Check #24
Close if ok with that proposal.

**Comment by luijoy** [comment]
@nemanjab17 Can this be closed? Cheers!

**Comment by nemanjab17** [comment]
@luijoy yes!
