### ISSUE TITLE
Is anchor supported code available?

### ISSUE THREAD

**Issue by james-ray** [StreamFlow-Finance/streamflow-timelock#31]
Hi, I see in js-sdk, stream.ts already supports anchor call.
But the code here is still based on entrypoint, is the new version code available be shared?

**Comment by imprfekt** [comment]
Hello @james-ray, this repository is no longer maintained, it's not the program used in `js-sdk`.

Latest version of Streamflow program is not open-source.
If `js-sdk` doesn't work for you and you need a support on a program level, use `rust-sdk` instead:

https://github.com/streamflow-finance/rust-sdk/

Thanks!
